COMMANDS = {
    'home': 'home',
    'back': 'back',
    'recent': 'recent',
    'scrollUp': 'scrollUp',
    'scrollDown': 'scrollDown',
    'pageRight': 'pageRight',
    'pageLeft': 'pageLeft',
    'volumeUp': 'volumeUp',
    'volumeDown': 'volumeDown',
    'volumeMute': 'volumeMute',
    'pageUp': 'pageUp',
    'pageDown': 'pageDown',
    'dpadUp': 'dpadUp',
    'dpadDown': 'dpadDown',
    'dpadLeft': 'dpadLeft',
    'dpadRight': 'dpadRight',
    'dpadCenter': 'dpadCenter',
    'dpadCenterLong': 'dpadCenterLong',
    'openNotification': 'openNotification',
    'takeScreenShot': 'takeScreenShot',
    'powerDialog': 'powerDialog',
    'lockScreen': 'lockScreen',
    'switchToTV': 'switchToTV',
    'mediaPrevious': 'mediaPrevious',
    'mediaNext': 'mediaNext',
    'mediaPlayPause': 'mediaPlayPause',
    'channelUp': 'channelUp',
    'channelDown': 'channelDown',
    'fastRewind': 'fastRewind',
    'fastForward': 'fastForward',
    'pressNumber 0': 'pressNumber 0',
    'pressNumber 1': 'pressNumber 1',
    'pressNumber 2': 'pressNumber 2',
    'pressNumber 3': 'pressNumber 3',
    'pressNumber 4': 'pressNumber 4',
    'pressNumber 5': 'pressNumber 5',
    'pressNumber 6': 'pressNumber 6',
    'pressNumber 7': 'pressNumber 7',
    'pressNumber 8': 'pressNumber 8',
    'pressNumber 9': 'pressNumber 9',
    'pressMenu': 'pressMenu',
    'keycodeGuide': 'keycodeGuide',
    'click': 'click',
    'longClick': 'longClick',
}